# Generated by Django 2.1.4 on 2019-01-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_item_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
