# Generated by Django 2.1.4 on 2019-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20190104_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
