from nutrition.models import CoreData
# from nutrition import dictionary

class Upload:

	def data(user_inputs, data, units):
		#calculate the 7th col in the model here: cal_per_gram. It just divides a number in values by a number in user_inputs
		# headers = ['name', 'state', 'data_source', 'notes', 'servingsize', 'servingsizeunits', 'cal_per_gram', 'Protein', 'Carbohydrates', 'Fattotal', 'DietaryFiber', 'Calories', 'Starch', 'TotalSugars', 'Monosaccharides', 'Fructose', 'Glucose', 'Galactose', 'Disaccharides', 'Lactose', 'Maltose', 'Sucrose', 'SolubleFiber', 'InsolubleFiber', 'OtherCarbohydrates', 'MonounsaturatedFat', 'PolyunsaturatedFat', 'SaturatedFat', 'TransFat', 'Cholesterol', 'Water', 'VitaminB1', 'VitaminB2', 'VitaminB3', 'VitaminB3NiacinEquivalents', 'VitaminB6', 'VitaminB12', 'Biotin', 'Choline', 'Folate', 'FolateDFE', 'Folatefood', 'PantothenicAcid', 'VitaminC', 'VitaminAInternationalUnitsIU', 'VitaminAmcgRetinolActivityEquivalentsRAE', 'VitaminAmcgRetinolEquivalentsRE', 'RetinolmcgRetinolEquivalentsRE', 'CarotenoidmcgRetinolEquivalentsRE', 'AlphaCarotene', 'BetaCarotene', 'BetaCaroteneEquivalents', 'Cryptoxanthin', 'LuteinandZeaxanthin', 'Lycopene', 'VitaminDInternationalUnitsIU', 'VitaminDmcg', 'VitaminEmgAlphaTocopherolEquivalentsATE', 'VitaminEInternationalUnitsIU', 'VitaminEmg', 'VitaminK', 'Boron', 'Calcium', 'Chloride', 'Chromium', 'Copper', 'Fluoride', 'Iodine', 'Iron', 'Magnesium', 'Manganese', 'Molybdenum', 'Phosphorus', 'Potassium', 'Selenium', 'Sodium', 'Zinc', 'Omega3FattyAcids', 'Omega6FattyAcids', 'a141Myristoleic', 'a151Pentadecenoic', 'a161Palmitol', 'a171Heptadecenoic', 'a181Oleic', 'a201Eicosenoic', 'a221Erucic', 'a241Nervonic', 'a182Linoleic', 'a182ConjugatedLinoleicCLA', 'a183Linolenic', 'a184Stearidonic', 'a203Eicosatrienoic', 'a204Arachidonic', 'a205EicosapentaenoicEPA', 'a225DocosapentaenoicDPA', 'a226DocosahexaenoicDHA', 'a40Butyric', 'a60Caproic', 'a80Caprylic', 'a100Capric', 'a120Lauric', 'a140Myristic', 'a150Pentadecanoic', 'a160Palmitic', 'a170Margaric', 'a180Stearic', 'a200Arachidic', 'a220Behenate', 'a240Lignoceric', 'Alanine', 'Arginine', 'AsparticAcid', 'Cysteine', 'GlutamicAcid', 'Glycine', 'Histidine', 'Isoleucine', 'Leucine', 'Lysine', 'Methionine', 'Phenylalanine', 'Proline', 'Serine', 'Threonine', 'Tryptophan', 'Tyrosine', 'Valine', 'Ash', 'OrganicAcidsTotal', 'AceticAcid', 'CitricAcid', 'LacticAcid', 'MalicAcid', 'Taurine', 'SugarAlcoholsTotal', 'Glycerol', 'Inositol', 'Mannitol', 'Sorbitol', 'Xylitol', 'ArtificialSweetenersTotal', 'Aspartame', 'Saccharin', 'Alcohol', 'Caffeine']
		# units_headers = ['uProtein', 'uCarbohydrates', 'uFattotal', 'uDietaryFiber', 'uCalories', 'uStarch', 'uTotalSugars', 'uMonosaccharides', 'uFructose', 'uGlucose', 'uGalactose', 'uDisaccharides', 'uLactose', 'uMaltose', 'uSucrose', 'uSolubleFiber', 'uInsolubleFiber', 'uOtherCarbohydrates', 'uMonounsaturatedFat', 'uPolyunsaturatedFat', 'uSaturatedFat', 'uTransFat', 'uCholesterol', 'uWater', 'uVitaminB1', 'uVitaminB2', 'uVitaminB3', 'uVitaminB3NiacinEquivalents', 'uVitaminB6', 'uVitaminB12', 'uBiotin', 'uCholine', 'uFolate', 'uFolateDFE', 'uFolatefood', 'uPantothenicAcid', 'uVitaminC', 'uVitaminAInternationalUnitsIU', 'uVitaminAmcgRetinolActivityEquivalentsRAE', 'uVitaminAmcgRetinolEquivalentsRE', 'uRetinolmcgRetinolEquivalentsRE', 'uCarotenoidmcgRetinolEquivalentsRE', 'uAlphaCarotene', 'uBetaCarotene', 'uBetaCaroteneEquivalents', 'uCryptoxanthin', 'uLuteinandZeaxanthin', 'uLycopene', 'uVitaminDInternationalUnitsIU', 'uVitaminDmcg', 'uVitaminEmgAlphaTocopherolEquivalentsATE', 'uVitaminEInternationalUnitsIU', 'uVitaminEmg', 'uVitaminK', 'uBoron', 'uCalcium', 'uChloride', 'uChromium', 'uCopper', 'uFluoride', 'uIodine', 'uIron', 'uMagnesium', 'uManganese', 'uMolybdenum', 'uPhosphorus', 'uPotassium', 'uSelenium', 'uSodium', 'uZinc', 'uOmega3FattyAcids', 'uOmega6FattyAcids', 'ua141Myristoleic', 'ua151Pentadecenoic', 'ua161Palmitol', 'ua171Heptadecenoic', 'ua181Oleic', 'ua201Eicosenoic', 'ua221Erucic', 'ua241Nervonic', 'ua182Linoleic', 'ua182ConjugatedLinoleicCLA', 'ua183Linolenic', 'ua184Stearidonic', 'ua203Eicosatrienoic', 'ua204Arachidonic', 'ua205EicosapentaenoicEPA', 'ua225DocosapentaenoicDPA', 'ua226DocosahexaenoicDHA', 'ua40Butyric', 'ua60Caproic', 'ua80Caprylic', 'ua100Capric', 'ua120Lauric', 'ua140Myristic', 'ua150Pentadecanoic', 'ua160Palmitic', 'ua170Margaric', 'ua180Stearic', 'ua200Arachidic', 'ua220Behenate', 'ua240Lignoceric', 'uAlanine', 'uArginine', 'uAsparticAcid', 'uCysteine', 'uGlutamicAcid', 'uGlycine', 'uHistidine', 'uIsoleucine', 'uLeucine', 'uLysine', 'uMethionine', 'uPhenylalanine', 'uProline', 'uSerine', 'uThreonine', 'uTryptophan', 'uTyrosine', 'uValine', 'uAsh', 'uOrganicAcidsTotal', 'uAceticAcid', 'uCitricAcid', 'uLacticAcid', 'uMalicAcid', 'uTaurine', 'uSugarAlcoholsTotal', 'uGlycerol', 'uInositol', 'uMannitol', 'uSorbitol', 'uXylitol', 'uArtificialSweetenersTotal', 'uAspartame', 'uSaccharin', 'uAlcohol', 'uCaffeine']
		
		cal_per_gram = [(float(data[4]) / float(user_inputs[4]))]
		# cal_per_gram = [decimal(cal_per_gram_calc)] 
		values = user_inputs + cal_per_gram + data 
		# cal_per_gram = [0.1]

		# values = user_inputs + cal_per_gram + data

		# cal_per_gram=values[6],
		CoreData.objects.create(name=values[0], state=values[1], data_source=values[2], notes=values[3], servingsize=values[4], servingsizeunits=values[5], cal_per_gram=values[6], Protein=values[7], Carbohydrates=values[8], Fattotal=values[9], DietaryFiber=values[10], Calories=values[11], Starch=values[12], TotalSugars=values[13], Monosaccharides=values[14], Fructose=values[15], Glucose=values[16], Galactose=values[17], Disaccharides=values[18], Lactose=values[19], Maltose=values[20], Sucrose=values[21], SolubleFiber=values[22], InsolubleFiber=values[23], OtherCarbohydrates=values[24], MonounsaturatedFat=values[25], PolyunsaturatedFat=values[26], SaturatedFat=values[27], TransFat=values[28], Cholesterol=values[29], Water=values[30], VitaminB1=values[31], VitaminB2=values[32], VitaminB3=values[33], VitaminB3NiacinEquivalents=values[34], VitaminB6=values[35], VitaminB12=values[36], Biotin=values[37], Choline=values[38], Folate=values[39], FolateDFE=values[40], Folatefood=values[41], PantothenicAcid=values[42], VitaminC=values[43], VitaminAInternationalUnitsIU=values[44], VitaminAmcgRetinolActivityEquivalentsRAE=values[45], VitaminAmcgRetinolEquivalentsRE=values[46], RetinolmcgRetinolEquivalentsRE=values[47], CarotenoidmcgRetinolEquivalentsRE=values[48], AlphaCarotene=values[49], BetaCarotene=values[50], BetaCaroteneEquivalents=values[51], Cryptoxanthin=values[52], LuteinandZeaxanthin=values[53], Lycopene=values[54], VitaminDInternationalUnitsIU=values[55], VitaminDmcg=values[56], VitaminEmgAlphaTocopherolEquivalentsATE=values[57], VitaminEInternationalUnitsIU=values[58], VitaminEmg=values[59], VitaminK=values[60], Boron=values[61], Calcium=values[62], Chloride=values[63], Chromium=values[64], Copper=values[65], Fluoride=values[66], Iodine=values[67], Iron=values[68], Magnesium=values[69], Manganese=values[70], Molybdenum=values[71], Phosphorus=values[72], Potassium=values[73], Selenium=values[74], Sodium=values[75], Zinc=values[76], Omega3FattyAcids=values[77], Omega6FattyAcids=values[78], a141Myristoleic=values[79], a151Pentadecenoic=values[80], a161Palmitol=values[81], a171Heptadecenoic=values[82], a181Oleic=values[83], a201Eicosenoic=values[84], a221Erucic=values[85], a241Nervonic=values[86], a182Linoleic=values[87], a182ConjugatedLinoleicCLA=values[88], a183Linolenic=values[89], a184Stearidonic=values[90], a203Eicosatrienoic=values[91], a204Arachidonic=values[92], a205EicosapentaenoicEPA=values[93], a225DocosapentaenoicDPA=values[94], a226DocosahexaenoicDHA=values[95], a40Butyric=values[96], a60Caproic=values[97], a80Caprylic=values[98], a100Capric=values[99], a120Lauric=values[100], a140Myristic=values[101], a150Pentadecanoic=values[102], a160Palmitic=values[103], a170Margaric=values[104], a180Stearic=values[105], a200Arachidic=values[106], a220Behenate=values[107], a240Lignoceric=values[108], Alanine=values[109], Arginine=values[110], AsparticAcid=values[111], Cysteine=values[112], GlutamicAcid=values[113], Glycine=values[114], Histidine=values[115], Isoleucine=values[116], Leucine=values[117], Lysine=values[118], Methionine=values[119], Phenylalanine=values[120], Proline=values[121], Serine=values[122], Threonine=values[123], Tryptophan=values[124], Tyrosine=values[125], Valine=values[126], Ash=values[127], OrganicAcidsTotal=values[128], AceticAcid=values[129], CitricAcid=values[130], LacticAcid=values[131], MalicAcid=values[132], Taurine=values[133], SugarAlcoholsTotal=values[134], Glycerol=values[135], Inositol=values[136], Mannitol=values[137], Sorbitol=values[138], Xylitol=values[139], ArtificialSweetenersTotal=values[140], Aspartame=values[141], Saccharin=values[142], Alcohol=values[143], Caffeine=values[144])
		
		update = CoreData.objects.filter(name=values[0])[0]
		update.uProtein = units[0]
		update.uCarbohydrates = units[1]
		update.uFattotal = units[2]
		update.uDietaryFiber = units[3]
		update.uCalories = units[4]
		update.uStarch = units[5]
		update.uTotalSugars = units[6]
		update.uMonosaccharides = units[7]
		update.uFructose = units[8]
		update.uGlucose = units[9]
		update.uGalactose = units[10]
		update.uDisaccharides = units[11]
		update.uLactose = units[12]
		update.uMaltose = units[13]
		update.uSucrose = units[14]
		update.uSolubleFiber = units[15]
		update.uInsolubleFiber = units[16]
		update.uOtherCarbohydrates = units[17]
		update.uMonounsaturatedFat = units[18]
		update.uPolyunsaturatedFat = units[19]
		update.uSaturatedFat = units[20]
		update.uTransFat = units[21]
		update.uCholesterol = units[22]
		update.uWater = units[23]
		update.uVitaminB1 = units[24]
		update.uVitaminB2 = units[25]
		update.uVitaminB3 = units[26]
		update.uVitaminB3NiacinEquivalents = units[27]
		update.uVitaminB6 = units[28]
		update.uVitaminB12 = units[29]
		update.uBiotin = units[30]
		update.uCholine = units[31]
		update.uFolate = units[32]
		update.uFolateDFE = units[33]
		update.uFolatefood = units[34]
		update.uPantothenicAcid = units[35]
		update.uVitaminC = units[36]
		update.uVitaminAInternationalUnitsIU = units[37]
		update.uVitaminAmcgRetinolActivityEquivalentsRAE = units[38]
		update.uVitaminAmcgRetinolEquivalentsRE = units[39]
		update.uRetinolmcgRetinolEquivalentsRE = units[40]
		update.uCarotenoidmcgRetinolEquivalentsRE = units[41]
		update.uAlphaCarotene = units[42]
		update.uBetaCarotene = units[43]
		update.uBetaCaroteneEquivalents = units[44]
		update.uCryptoxanthin = units[45]
		update.uLuteinandZeaxanthin = units[46]
		update.uLycopene = units[47]
		update.uVitaminDInternationalUnitsIU = units[48]
		update.uVitaminDmcg = units[49]
		update.uVitaminEmgAlphaTocopherolEquivalentsATE = units[50]
		update.uVitaminEInternationalUnitsIU = units[51]
		update.uVitaminEmg = units[52]
		update.uVitaminK = units[53]
		update.uBoron = units[54]
		update.uCalcium = units[55]
		update.uChloride = units[56]
		update.uChromium = units[57]
		update.uCopper = units[58]
		update.uFluoride = units[59]
		update.uIodine = units[60]
		update.uIron = units[61]
		update.uMagnesium = units[62]
		update.uManganese = units[63]
		update.uMolybdenum = units[64]
		update.uPhosphorus = units[65]
		update.uPotassium = units[66]
		update.uSelenium = units[67]
		update.uSodium = units[68]
		update.uZinc = units[69]
		update.uOmega3FattyAcids = units[70]
		update.uOmega6FattyAcids = units[71]
		update.ua141Myristoleic = units[72]
		update.ua151Pentadecenoic = units[73]
		update.ua161Palmitol = units[74]
		update.ua171Heptadecenoic = units[75]
		update.ua181Oleic = units[76]
		update.ua201Eicosenoic = units[77]
		update.ua221Erucic = units[78]
		update.ua241Nervonic = units[79]
		update.ua182Linoleic = units[80]
		update.ua182ConjugatedLinoleicCLA = units[81]
		update.ua183Linolenic = units[82]
		update.ua184Stearidonic = units[83]
		update.ua203Eicosatrienoic = units[84]
		update.ua204Arachidonic = units[85]
		update.ua205EicosapentaenoicEPA = units[86]
		update.ua225DocosapentaenoicDPA = units[87]
		update.ua226DocosahexaenoicDHA = units[88]
		update.ua40Butyric = units[89]
		update.ua60Caproic = units[90]
		update.ua80Caprylic = units[91]
		update.ua100Capric = units[92]
		update.ua120Lauric = units[93]
		update.ua140Myristic = units[94]
		update.ua150Pentadecanoic = units[95]
		update.ua160Palmitic = units[96]
		update.ua170Margaric = units[97]
		update.ua180Stearic = units[98]
		update.ua200Arachidic = units[99]
		update.ua220Behenate = units[100]
		update.ua240Lignoceric = units[101]
		update.uAlanine = units[102]
		update.uArginine = units[103]
		update.uAsparticAcid = units[104]
		update.uCysteine = units[105]
		update.uGlutamicAcid = units[106]
		update.uGlycine = units[107]
		update.uHistidine = units[108]
		update.uIsoleucine = units[109]
		update.uLeucine = units[110]
		update.uLysine = units[111]
		update.uMethionine = units[112]
		update.uPhenylalanine = units[113]
		update.uProline = units[114]
		update.uSerine = units[115]
		update.uThreonine = units[116]
		update.uTryptophan = units[117]
		update.uTyrosine = units[118]
		update.uValine = units[119]
		update.uAsh = units[120]
		update.uOrganicAcidsTotal = units[121]
		update.uAceticAcid = units[122]
		update.uCitricAcid = units[123]
		update.uLacticAcid = units[124]
		update.uMalicAcid = units[125]
		update.uTaurine = units[126]
		update.uSugarAlcoholsTotal = units[127]
		update.uGlycerol = units[128]
		update.uInositol = units[129]
		update.uMannitol = units[130]
		update.uSorbitol = units[131]
		update.uXylitol = units[132]
		update.uArtificialSweetenersTotal = units[133]
		update.uAspartame = units[134]
		update.uSaccharin = units[135]
		update.uAlcohol = units[136]
		update.uCaffeine = units[137]

		update.save()
 
	