from django.db import models

# Create your models here.
class CoreData(models.Model):
	name = models.TextField()
	state = models.TextField()
	data_source = models.TextField()
	notes = models.TextField()
	servingsize = models.DecimalField(decimal_places=3, max_digits=20)
	servingsizeunits = models.TextField()
	cal_per_gram = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	Protein = models.DecimalField(decimal_places=3, max_digits=20)
	Carbohydrates = models.DecimalField(decimal_places=3, max_digits=20)
	Fattotal = models.DecimalField(decimal_places=3, max_digits=20)
	DietaryFiber = models.DecimalField(decimal_places=3, max_digits=20)
	Calories = models.DecimalField(decimal_places=3, max_digits=20)
	Starch = models.DecimalField(decimal_places=3, max_digits=20)
	TotalSugars = models.DecimalField(decimal_places=3, max_digits=20)
	Monosaccharides = models.DecimalField(decimal_places=3, max_digits=20)
	Fructose = models.DecimalField(decimal_places=3, max_digits=20)
	Glucose = models.DecimalField(decimal_places=3, max_digits=20)
	Galactose = models.DecimalField(decimal_places=3, max_digits=20)
	Disaccharides = models.DecimalField(decimal_places=3, max_digits=20)
	Lactose = models.DecimalField(decimal_places=3, max_digits=20)
	Maltose = models.DecimalField(decimal_places=3, max_digits=20)
	Sucrose = models.DecimalField(decimal_places=3, max_digits=20)
	SolubleFiber = models.DecimalField(decimal_places=3, max_digits=20)
	InsolubleFiber = models.DecimalField(decimal_places=3, max_digits=20)
	OtherCarbohydrates = models.DecimalField(decimal_places=3, max_digits=20)
	MonounsaturatedFat = models.DecimalField(decimal_places=3, max_digits=20)
	PolyunsaturatedFat = models.DecimalField(decimal_places=3, max_digits=20)
	SaturatedFat = models.DecimalField(decimal_places=3, max_digits=20)
	TransFat = models.DecimalField(decimal_places=3, max_digits=20)
	Cholesterol = models.DecimalField(decimal_places=3, max_digits=20)
	Water = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB1 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB2 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB3 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB3NiacinEquivalents = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB6 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB12 = models.DecimalField(decimal_places=3, max_digits=20)
	Biotin = models.DecimalField(decimal_places=3, max_digits=20)
	Choline = models.DecimalField(decimal_places=3, max_digits=20)
	Folate = models.DecimalField(decimal_places=3, max_digits=20)
	FolateDFE = models.DecimalField(decimal_places=3, max_digits=20)
	Folatefood = models.DecimalField(decimal_places=3, max_digits=20)
	PantothenicAcid = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminC = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminAInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminAmcgRetinolActivityEquivalentsRAE = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminAmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20)
	RetinolmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20)
	CarotenoidmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20)
	AlphaCarotene = models.DecimalField(decimal_places=3, max_digits=20)
	BetaCarotene = models.DecimalField(decimal_places=3, max_digits=20)
	BetaCaroteneEquivalents = models.DecimalField(decimal_places=3, max_digits=20)
	Cryptoxanthin = models.DecimalField(decimal_places=3, max_digits=20)
	LuteinandZeaxanthin = models.DecimalField(decimal_places=3, max_digits=20)
	Lycopene = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminDInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminDmcg = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminEmgAlphaTocopherolEquivalentsATE = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminEInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminEmg = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminK = models.DecimalField(decimal_places=3, max_digits=20)
	Boron = models.DecimalField(decimal_places=3, max_digits=20)
	Calcium = models.DecimalField(decimal_places=3, max_digits=20)
	Chloride = models.DecimalField(decimal_places=3, max_digits=20)
	Chromium = models.DecimalField(decimal_places=3, max_digits=20)
	Copper = models.DecimalField(decimal_places=3, max_digits=20)
	Fluoride = models.DecimalField(decimal_places=3, max_digits=20)
	Iodine = models.DecimalField(decimal_places=3, max_digits=20)
	Iron = models.DecimalField(decimal_places=3, max_digits=20)
	Magnesium = models.DecimalField(decimal_places=3, max_digits=20)
	Manganese = models.DecimalField(decimal_places=3, max_digits=20)
	Molybdenum = models.DecimalField(decimal_places=3, max_digits=20)
	Phosphorus = models.DecimalField(decimal_places=3, max_digits=20)
	Potassium = models.DecimalField(decimal_places=3, max_digits=20)
	Selenium = models.DecimalField(decimal_places=3, max_digits=20)
	Sodium = models.DecimalField(decimal_places=3, max_digits=20)
	Zinc = models.DecimalField(decimal_places=3, max_digits=20)
	Omega3FattyAcids = models.DecimalField(decimal_places=3, max_digits=20)
	Omega6FattyAcids = models.DecimalField(decimal_places=3, max_digits=20)
	a141Myristoleic = models.DecimalField(decimal_places=3, max_digits=20)
	a151Pentadecenoic = models.DecimalField(decimal_places=3, max_digits=20)
	a161Palmitol = models.DecimalField(decimal_places=3, max_digits=20)
	a171Heptadecenoic = models.DecimalField(decimal_places=3, max_digits=20)
	a181Oleic = models.DecimalField(decimal_places=3, max_digits=20)
	a201Eicosenoic = models.DecimalField(decimal_places=3, max_digits=20)
	a221Erucic = models.DecimalField(decimal_places=3, max_digits=20)
	a241Nervonic = models.DecimalField(decimal_places=3, max_digits=20)
	a182Linoleic = models.DecimalField(decimal_places=3, max_digits=20)
	a182ConjugatedLinoleicCLA = models.DecimalField(decimal_places=3, max_digits=20)
	a183Linolenic = models.DecimalField(decimal_places=3, max_digits=20)
	a184Stearidonic = models.DecimalField(decimal_places=3, max_digits=20)
	a203Eicosatrienoic = models.DecimalField(decimal_places=3, max_digits=20)
	a204Arachidonic = models.DecimalField(decimal_places=3, max_digits=20)
	a205EicosapentaenoicEPA = models.DecimalField(decimal_places=3, max_digits=20)
	a225DocosapentaenoicDPA = models.DecimalField(decimal_places=3, max_digits=20)
	a226DocosahexaenoicDHA = models.DecimalField(decimal_places=3, max_digits=20)
	a40Butyric = models.DecimalField(decimal_places=3, max_digits=20)
	a60Caproic = models.DecimalField(decimal_places=3, max_digits=20)
	a80Caprylic = models.DecimalField(decimal_places=3, max_digits=20)
	a100Capric = models.DecimalField(decimal_places=3, max_digits=20)
	a120Lauric = models.DecimalField(decimal_places=3, max_digits=20)
	a140Myristic = models.DecimalField(decimal_places=3, max_digits=20)
	a150Pentadecanoic = models.DecimalField(decimal_places=3, max_digits=20)
	a160Palmitic = models.DecimalField(decimal_places=3, max_digits=20)
	a170Margaric = models.DecimalField(decimal_places=3, max_digits=20)
	a180Stearic = models.DecimalField(decimal_places=3, max_digits=20)
	a200Arachidic = models.DecimalField(decimal_places=3, max_digits=20)
	a220Behenate = models.DecimalField(decimal_places=3, max_digits=20)
	a240Lignoceric = models.DecimalField(decimal_places=3, max_digits=20)
	Alanine = models.DecimalField(decimal_places=3, max_digits=20)
	Arginine = models.DecimalField(decimal_places=3, max_digits=20)
	AsparticAcid = models.DecimalField(decimal_places=3, max_digits=20)
	Cysteine = models.DecimalField(decimal_places=3, max_digits=20)
	GlutamicAcid = models.DecimalField(decimal_places=3, max_digits=20)
	Glycine = models.DecimalField(decimal_places=3, max_digits=20)
	Histidine = models.DecimalField(decimal_places=3, max_digits=20)
	Isoleucine = models.DecimalField(decimal_places=3, max_digits=20)
	Leucine = models.DecimalField(decimal_places=3, max_digits=20)
	Lysine = models.DecimalField(decimal_places=3, max_digits=20)
	Methionine = models.DecimalField(decimal_places=3, max_digits=20)
	Phenylalanine = models.DecimalField(decimal_places=3, max_digits=20)
	Proline = models.DecimalField(decimal_places=3, max_digits=20)
	Serine = models.DecimalField(decimal_places=3, max_digits=20)
	Threonine = models.DecimalField(decimal_places=3, max_digits=20)
	Tryptophan = models.DecimalField(decimal_places=3, max_digits=20)
	Tyrosine = models.DecimalField(decimal_places=3, max_digits=20)
	Valine = models.DecimalField(decimal_places=3, max_digits=20)
	Ash = models.DecimalField(decimal_places=3, max_digits=20)
	OrganicAcidsTotal = models.DecimalField(decimal_places=3, max_digits=20)
	AceticAcid = models.DecimalField(decimal_places=3, max_digits=20)
	CitricAcid = models.DecimalField(decimal_places=3, max_digits=20)
	LacticAcid = models.DecimalField(decimal_places=3, max_digits=20)
	MalicAcid = models.DecimalField(decimal_places=3, max_digits=20)
	Taurine = models.DecimalField(decimal_places=3, max_digits=20)
	SugarAlcoholsTotal = models.DecimalField(decimal_places=3, max_digits=20)
	Glycerol = models.DecimalField(decimal_places=3, max_digits=20)
	Inositol = models.DecimalField(decimal_places=3, max_digits=20)
	Mannitol = models.DecimalField(decimal_places=3, max_digits=20)
	Sorbitol = models.DecimalField(decimal_places=3, max_digits=20)
	Xylitol = models.DecimalField(decimal_places=3, max_digits=20)
	ArtificialSweetenersTotal = models.DecimalField(decimal_places=3, max_digits=20)
	Aspartame = models.DecimalField(decimal_places=3, max_digits=20)
	Saccharin = models.DecimalField(decimal_places=3, max_digits=20)
	Alcohol = models.DecimalField(decimal_places=3, max_digits=20)
	Caffeine = models.DecimalField(decimal_places=3, max_digits=20)
	uProtein = models.TextField(default='none')
	uCarbohydrates = models.TextField(default='none')
	uFattotal = models.TextField(default='none')
	uDietaryFiber = models.TextField(default='none')
	uCalories = models.TextField(default='none')
	uStarch = models.TextField(default='none')
	uTotalSugars = models.TextField(default='none')
	uMonosaccharides = models.TextField(default='none')
	uFructose = models.TextField(default='none')
	uGlucose = models.TextField(default='none')
	uGalactose = models.TextField(default='none')
	uDisaccharides = models.TextField(default='none')
	uLactose = models.TextField(default='none')
	uMaltose = models.TextField(default='none')
	uSucrose = models.TextField(default='none')
	uSolubleFiber = models.TextField(default='none')
	uInsolubleFiber = models.TextField(default='none')
	uOtherCarbohydrates = models.TextField(default='none')
	uMonounsaturatedFat = models.TextField(default='none')
	uPolyunsaturatedFat = models.TextField(default='none')
	uSaturatedFat = models.TextField(default='none')
	uTransFat = models.TextField(default='none')
	uCholesterol = models.TextField(default='none')
	uWater = models.TextField(default='none')
	uVitaminB1 = models.TextField(default='none')
	uVitaminB2 = models.TextField(default='none')
	uVitaminB3 = models.TextField(default='none')
	uVitaminB3NiacinEquivalents = models.TextField(default='none')
	uVitaminB6 = models.TextField(default='none')
	uVitaminB12 = models.TextField(default='none')
	uBiotin = models.TextField(default='none')
	uCholine = models.TextField(default='none')
	uFolate = models.TextField(default='none')
	uFolateDFE = models.TextField(default='none')
	uFolatefood = models.TextField(default='none')
	uPantothenicAcid = models.TextField(default='none')
	uVitaminC = models.TextField(default='none')
	uVitaminAInternationalUnitsIU = models.TextField(default='none')
	uVitaminAmcgRetinolActivityEquivalentsRAE = models.TextField(default='none')
	uVitaminAmcgRetinolEquivalentsRE = models.TextField(default='none')
	uRetinolmcgRetinolEquivalentsRE = models.TextField(default='none')
	uCarotenoidmcgRetinolEquivalentsRE = models.TextField(default='none')
	uAlphaCarotene = models.TextField(default='none')
	uBetaCarotene = models.TextField(default='none')
	uBetaCaroteneEquivalents = models.TextField(default='none')
	uCryptoxanthin = models.TextField(default='none')
	uLuteinandZeaxanthin = models.TextField(default='none')
	uLycopene = models.TextField(default='none')
	uVitaminDInternationalUnitsIU = models.TextField(default='none')
	uVitaminDmcg = models.TextField(default='none')
	uVitaminEmgAlphaTocopherolEquivalentsATE = models.TextField(default='none')
	uVitaminEInternationalUnitsIU = models.TextField(default='none')
	uVitaminEmg = models.TextField(default='none')
	uVitaminK = models.TextField(default='none')
	uBoron = models.TextField(default='none')
	uCalcium = models.TextField(default='none')
	uChloride = models.TextField(default='none')
	uChromium = models.TextField(default='none')
	uCopper = models.TextField(default='none')
	uFluoride = models.TextField(default='none')
	uIodine = models.TextField(default='none')
	uIron = models.TextField(default='none')
	uMagnesium = models.TextField(default='none')
	uManganese = models.TextField(default='none')
	uMolybdenum = models.TextField(default='none')
	uPhosphorus = models.TextField(default='none')
	uPotassium = models.TextField(default='none')
	uSelenium = models.TextField(default='none')
	uSodium = models.TextField(default='none')
	uZinc = models.TextField(default='none')
	uOmega3FattyAcids = models.TextField(default='none')
	uOmega6FattyAcids = models.TextField(default='none')
	ua141Myristoleic = models.TextField(default='none')
	ua151Pentadecenoic = models.TextField(default='none')
	ua161Palmitol = models.TextField(default='none')
	ua171Heptadecenoic = models.TextField(default='none')
	ua181Oleic = models.TextField(default='none')
	ua201Eicosenoic = models.TextField(default='none')
	ua221Erucic = models.TextField(default='none')
	ua241Nervonic = models.TextField(default='none')
	ua182Linoleic = models.TextField(default='none')
	ua182ConjugatedLinoleicCLA = models.TextField(default='none')
	ua183Linolenic = models.TextField(default='none')
	ua184Stearidonic = models.TextField(default='none')
	ua203Eicosatrienoic = models.TextField(default='none')
	ua204Arachidonic = models.TextField(default='none')
	ua205EicosapentaenoicEPA = models.TextField(default='none')
	ua225DocosapentaenoicDPA = models.TextField(default='none')
	ua226DocosahexaenoicDHA = models.TextField(default='none')
	ua40Butyric = models.TextField(default='none')
	ua60Caproic = models.TextField(default='none')
	ua80Caprylic = models.TextField(default='none')
	ua100Capric = models.TextField(default='none')
	ua120Lauric = models.TextField(default='none')
	ua140Myristic = models.TextField(default='none')
	ua150Pentadecanoic = models.TextField(default='none')
	ua160Palmitic = models.TextField(default='none')
	ua170Margaric = models.TextField(default='none')
	ua180Stearic = models.TextField(default='none')
	ua200Arachidic = models.TextField(default='none')
	ua220Behenate = models.TextField(default='none')
	ua240Lignoceric = models.TextField(default='none')
	uAlanine = models.TextField(default='none')
	uArginine = models.TextField(default='none')
	uAsparticAcid = models.TextField(default='none')
	uCysteine = models.TextField(default='none')
	uGlutamicAcid = models.TextField(default='none')
	uGlycine = models.TextField(default='none')
	uHistidine = models.TextField(default='none')
	uIsoleucine = models.TextField(default='none')
	uLeucine = models.TextField(default='none')
	uLysine = models.TextField(default='none')
	uMethionine = models.TextField(default='none')
	uPhenylalanine = models.TextField(default='none')
	uProline = models.TextField(default='none')
	uSerine = models.TextField(default='none')
	uThreonine = models.TextField(default='none')
	uTryptophan = models.TextField(default='none')
	uTyrosine = models.TextField(default='none')
	uValine = models.TextField(default='none')
	uAsh = models.TextField(default='none')
	uOrganicAcidsTotal = models.TextField(default='none')
	uAceticAcid = models.TextField(default='none')
	uCitricAcid = models.TextField(default='none')
	uLacticAcid = models.TextField(default='none')
	uMalicAcid = models.TextField(default='none')
	uTaurine = models.TextField(default='none')
	uSugarAlcoholsTotal = models.TextField(default='none')
	uGlycerol = models.TextField(default='none')
	uInositol = models.TextField(default='none')
	uMannitol = models.TextField(default='none')
	uSorbitol = models.TextField(default='none')
	uXylitol = models.TextField(default='none')
	uArtificialSweetenersTotal = models.TextField(default='none')
	uAspartame = models.TextField(default='none')
	uSaccharin = models.TextField(default='none')
	uAlcohol = models.TextField(default='none')
	uCaffeine = models.TextField(default='none')


	def __str__(self):
		return str(self.name)

class Recipe(models.Model):
	name = models.CharField(max_length=50)
	instructions = models.TextField()
	source = models.TextField()
	tools_to_make = models.TextField()
	serving_instructions = models.TextField()
	tools_to_serve = models.TextField()

	def __str__(self):
		return self.name



class Item(models.Model):
	cost_based_on_grams = models.DecimalField(decimal_places=5, max_digits=20, default=0)
	cost_based_on_cal = models.DecimalField(decimal_places=5, max_digits=20, default=0)
	weekly_cost = models.DecimalField(decimal_places=5, max_digits=20, default=0)
	cost_per_g_protein = models.DecimalField(decimal_places=5, max_digits=20, default=0)
	cost_per_g_fiber = models.DecimalField(decimal_places=5, max_digits=20, default=0)
	name = models.ForeignKey(CoreData, on_delete=models.CASCADE)
	active = models.BooleanField(default=True)
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
	grams = models.DecimalField(decimal_places=3, max_digits=7)
	weekly_grams = models.DecimalField(decimal_places=3, max_digits=7, default=0)
	units = models.TextField(default='none')
	conversion = models.DecimalField(decimal_places=3, max_digits=7)
	cost_per_100_cal = models.DecimalField(decimal_places=3, max_digits=20)
	cost_per_gram = models.DecimalField(decimal_places=5, max_digits=20, default=0)
	monday_1 = models.BooleanField(default=False)
	monday_2 = models.BooleanField(default=False)
	monday_3 = models.BooleanField(default=False)
	tuesday_1 = models.BooleanField(default=False)
	tuesday_2 = models.BooleanField(default=False)
	tuesday_3 = models.BooleanField(default=False)
	wednesday_1 = models.BooleanField(default=False)
	wednesday_2 = models.BooleanField(default=False)
	wednesday_3 = models.BooleanField(default=False)
	thursday_1 = models.BooleanField(default=False)
	thursday_2 = models.BooleanField(default=False)
	thursday_3 = models.BooleanField(default=False)
	friday_1 = models.BooleanField(default=False)
	friday_2 = models.BooleanField(default=False)
	friday_3 = models.BooleanField(default=False)
	saturday_1 = models.BooleanField(default=False)
	saturday_2 = models.BooleanField(default=False)
	saturday_3 = models.BooleanField(default=False)
	sunday_1 = models.BooleanField(default=False)
	sunday_2 = models.BooleanField(default=False)
	sunday_3 = models.BooleanField(default=False)
	Protein = models.DecimalField(decimal_places=3, max_digits=20)
	Carbohydrates = models.DecimalField(decimal_places=3, max_digits=20)
	Fattotal = models.DecimalField(decimal_places=3, max_digits=20)
	DietaryFiber = models.DecimalField(decimal_places=3, max_digits=20)
	Calories = models.DecimalField(decimal_places=3, max_digits=20)
	Starch = models.DecimalField(decimal_places=3, max_digits=20)
	TotalSugars = models.DecimalField(decimal_places=3, max_digits=20)
	Monosaccharides = models.DecimalField(decimal_places=3, max_digits=20)
	Fructose = models.DecimalField(decimal_places=3, max_digits=20)
	Glucose = models.DecimalField(decimal_places=3, max_digits=20)
	Galactose = models.DecimalField(decimal_places=3, max_digits=20)
	Disaccharides = models.DecimalField(decimal_places=3, max_digits=20)
	Lactose = models.DecimalField(decimal_places=3, max_digits=20)
	Maltose = models.DecimalField(decimal_places=3, max_digits=20)
	Sucrose = models.DecimalField(decimal_places=3, max_digits=20)
	SolubleFiber = models.DecimalField(decimal_places=3, max_digits=20)
	InsolubleFiber = models.DecimalField(decimal_places=3, max_digits=20)
	OtherCarbohydrates = models.DecimalField(decimal_places=3, max_digits=20)
	MonounsaturatedFat = models.DecimalField(decimal_places=3, max_digits=20)
	PolyunsaturatedFat = models.DecimalField(decimal_places=3, max_digits=20)
	SaturatedFat = models.DecimalField(decimal_places=3, max_digits=20)
	TransFat = models.DecimalField(decimal_places=3, max_digits=20)
	Cholesterol = models.DecimalField(decimal_places=3, max_digits=20)
	Water = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB1 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB2 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB3 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB3NiacinEquivalents = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB6 = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminB12 = models.DecimalField(decimal_places=3, max_digits=20)
	Biotin = models.DecimalField(decimal_places=3, max_digits=20)
	Choline = models.DecimalField(decimal_places=3, max_digits=20)
	Folate = models.DecimalField(decimal_places=3, max_digits=20)
	FolateDFE = models.DecimalField(decimal_places=3, max_digits=20)
	Folatefood = models.DecimalField(decimal_places=3, max_digits=20)
	PantothenicAcid = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminC = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminAInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminAmcgRetinolActivityEquivalentsRAE = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminAmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20)
	RetinolmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20)
	CarotenoidmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20)
	AlphaCarotene = models.DecimalField(decimal_places=3, max_digits=20)
	BetaCarotene = models.DecimalField(decimal_places=3, max_digits=20)
	BetaCaroteneEquivalents = models.DecimalField(decimal_places=3, max_digits=20)
	Cryptoxanthin = models.DecimalField(decimal_places=3, max_digits=20)
	LuteinandZeaxanthin = models.DecimalField(decimal_places=3, max_digits=20)
	Lycopene = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminDInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminDmcg = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminEmgAlphaTocopherolEquivalentsATE = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminEInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminEmg = models.DecimalField(decimal_places=3, max_digits=20)
	VitaminK = models.DecimalField(decimal_places=3, max_digits=20)
	Boron = models.DecimalField(decimal_places=3, max_digits=20)
	Calcium = models.DecimalField(decimal_places=3, max_digits=20)
	Chloride = models.DecimalField(decimal_places=3, max_digits=20)
	Chromium = models.DecimalField(decimal_places=3, max_digits=20)
	Copper = models.DecimalField(decimal_places=3, max_digits=20)
	Fluoride = models.DecimalField(decimal_places=3, max_digits=20)
	Iodine = models.DecimalField(decimal_places=3, max_digits=20)
	Iron = models.DecimalField(decimal_places=3, max_digits=20)
	Magnesium = models.DecimalField(decimal_places=3, max_digits=20)
	Manganese = models.DecimalField(decimal_places=3, max_digits=20)
	Molybdenum = models.DecimalField(decimal_places=3, max_digits=20)
	Phosphorus = models.DecimalField(decimal_places=3, max_digits=20)
	Potassium = models.DecimalField(decimal_places=3, max_digits=20)
	Selenium = models.DecimalField(decimal_places=3, max_digits=20)
	Sodium = models.DecimalField(decimal_places=3, max_digits=20)
	Zinc = models.DecimalField(decimal_places=3, max_digits=20)
	Omega3FattyAcids = models.DecimalField(decimal_places=3, max_digits=20)
	Omega6FattyAcids = models.DecimalField(decimal_places=3, max_digits=20)
	a141Myristoleic = models.DecimalField(decimal_places=3, max_digits=20)
	a151Pentadecenoic = models.DecimalField(decimal_places=3, max_digits=20)
	a161Palmitol = models.DecimalField(decimal_places=3, max_digits=20)
	a171Heptadecenoic = models.DecimalField(decimal_places=3, max_digits=20)
	a181Oleic = models.DecimalField(decimal_places=3, max_digits=20)
	a201Eicosenoic = models.DecimalField(decimal_places=3, max_digits=20)
	a221Erucic = models.DecimalField(decimal_places=3, max_digits=20)
	a241Nervonic = models.DecimalField(decimal_places=3, max_digits=20)
	a182Linoleic = models.DecimalField(decimal_places=3, max_digits=20)
	a182ConjugatedLinoleicCLA = models.DecimalField(decimal_places=3, max_digits=20)
	a183Linolenic = models.DecimalField(decimal_places=3, max_digits=20)
	a184Stearidonic = models.DecimalField(decimal_places=3, max_digits=20)
	a203Eicosatrienoic = models.DecimalField(decimal_places=3, max_digits=20)
	a204Arachidonic = models.DecimalField(decimal_places=3, max_digits=20)
	a205EicosapentaenoicEPA = models.DecimalField(decimal_places=3, max_digits=20)
	a225DocosapentaenoicDPA = models.DecimalField(decimal_places=3, max_digits=20)
	a226DocosahexaenoicDHA = models.DecimalField(decimal_places=3, max_digits=20)
	a40Butyric = models.DecimalField(decimal_places=3, max_digits=20)
	a60Caproic = models.DecimalField(decimal_places=3, max_digits=20)
	a80Caprylic = models.DecimalField(decimal_places=3, max_digits=20)
	a100Capric = models.DecimalField(decimal_places=3, max_digits=20)
	a120Lauric = models.DecimalField(decimal_places=3, max_digits=20)
	a140Myristic = models.DecimalField(decimal_places=3, max_digits=20)
	a150Pentadecanoic = models.DecimalField(decimal_places=3, max_digits=20)
	a160Palmitic = models.DecimalField(decimal_places=3, max_digits=20)
	a170Margaric = models.DecimalField(decimal_places=3, max_digits=20)
	a180Stearic = models.DecimalField(decimal_places=3, max_digits=20)
	a200Arachidic = models.DecimalField(decimal_places=3, max_digits=20)
	a220Behenate = models.DecimalField(decimal_places=3, max_digits=20)
	a240Lignoceric = models.DecimalField(decimal_places=3, max_digits=20)
	Alanine = models.DecimalField(decimal_places=3, max_digits=20)
	Arginine = models.DecimalField(decimal_places=3, max_digits=20)
	AsparticAcid = models.DecimalField(decimal_places=3, max_digits=20)
	Cysteine = models.DecimalField(decimal_places=3, max_digits=20)
	GlutamicAcid = models.DecimalField(decimal_places=3, max_digits=20)
	Glycine = models.DecimalField(decimal_places=3, max_digits=20)
	Histidine = models.DecimalField(decimal_places=3, max_digits=20)
	Isoleucine = models.DecimalField(decimal_places=3, max_digits=20)
	Leucine = models.DecimalField(decimal_places=3, max_digits=20)
	Lysine = models.DecimalField(decimal_places=3, max_digits=20)
	Methionine = models.DecimalField(decimal_places=3, max_digits=20)
	Phenylalanine = models.DecimalField(decimal_places=3, max_digits=20)
	Proline = models.DecimalField(decimal_places=3, max_digits=20)
	Serine = models.DecimalField(decimal_places=3, max_digits=20)
	Threonine = models.DecimalField(decimal_places=3, max_digits=20)
	Tryptophan = models.DecimalField(decimal_places=3, max_digits=20)
	Tyrosine = models.DecimalField(decimal_places=3, max_digits=20)
	Valine = models.DecimalField(decimal_places=3, max_digits=20)
	Ash = models.DecimalField(decimal_places=3, max_digits=20)
	OrganicAcidsTotal = models.DecimalField(decimal_places=3, max_digits=20)
	AceticAcid = models.DecimalField(decimal_places=3, max_digits=20)
	CitricAcid = models.DecimalField(decimal_places=3, max_digits=20)
	LacticAcid = models.DecimalField(decimal_places=3, max_digits=20)
	MalicAcid = models.DecimalField(decimal_places=3, max_digits=20)
	Taurine = models.DecimalField(decimal_places=3, max_digits=20)
	SugarAlcoholsTotal = models.DecimalField(decimal_places=3, max_digits=20)
	Glycerol = models.DecimalField(decimal_places=3, max_digits=20)
	Inositol = models.DecimalField(decimal_places=3, max_digits=20)
	Mannitol = models.DecimalField(decimal_places=3, max_digits=20)
	Sorbitol = models.DecimalField(decimal_places=3, max_digits=20)
	Xylitol = models.DecimalField(decimal_places=3, max_digits=20)
	ArtificialSweetenersTotal = models.DecimalField(decimal_places=3, max_digits=20)
	Aspartame = models.DecimalField(decimal_places=3, max_digits=20)
	Saccharin = models.DecimalField(decimal_places=3, max_digits=20)
	Alcohol = models.DecimalField(decimal_places=3, max_digits=20)
	Caffeine = models.DecimalField(decimal_places=3, max_digits=20)
	week_Protein = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Carbohydrates = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Fattotal = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_DietaryFiber = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Calories = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Starch = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_TotalSugars = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Monosaccharides = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Fructose = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Glucose = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Galactose = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Disaccharides = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Lactose = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Maltose = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Sucrose = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_SolubleFiber = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_InsolubleFiber = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_OtherCarbohydrates = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_MonounsaturatedFat = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_PolyunsaturatedFat = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_SaturatedFat = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_TransFat = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Cholesterol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Water = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminB1 = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminB2 = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminB3 = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminB3NiacinEquivalents = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminB6 = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminB12 = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Biotin = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Choline = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Folate = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_FolateDFE = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Folatefood = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_PantothenicAcid = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminC = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminAInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminAmcgRetinolActivityEquivalentsRAE = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminAmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_RetinolmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_CarotenoidmcgRetinolEquivalentsRE = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_AlphaCarotene = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_BetaCarotene = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_BetaCaroteneEquivalents = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Cryptoxanthin = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_LuteinandZeaxanthin = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Lycopene = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminDInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminDmcg = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminEmgAlphaTocopherolEquivalentsATE = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminEInternationalUnitsIU = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminEmg = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_VitaminK = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Boron = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Calcium = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Chloride = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Chromium = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Copper = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Fluoride = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Iodine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Iron = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Magnesium = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Manganese = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Molybdenum = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Phosphorus = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Potassium = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Selenium = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Sodium = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Zinc = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Omega3FattyAcids = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Omega6FattyAcids = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a141Myristoleic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a151Pentadecenoic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a161Palmitol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a171Heptadecenoic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a181Oleic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a201Eicosenoic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a221Erucic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a241Nervonic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a182Linoleic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a182ConjugatedLinoleicCLA = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a183Linolenic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a184Stearidonic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a203Eicosatrienoic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a204Arachidonic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a205EicosapentaenoicEPA = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a225DocosapentaenoicDPA = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a226DocosahexaenoicDHA = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a40Butyric = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a60Caproic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a80Caprylic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a100Capric = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a120Lauric = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a140Myristic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a150Pentadecanoic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a160Palmitic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a170Margaric = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a180Stearic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a200Arachidic = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a220Behenate = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_a240Lignoceric = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Alanine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Arginine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_AsparticAcid = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Cysteine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_GlutamicAcid = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Glycine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Histidine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Isoleucine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Leucine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Lysine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Methionine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Phenylalanine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Proline = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Serine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Threonine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Tryptophan = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Tyrosine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Valine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Ash = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_OrganicAcidsTotal = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_AceticAcid = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_CitricAcid = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_LacticAcid = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_MalicAcid = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Taurine = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_SugarAlcoholsTotal = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Glycerol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Inositol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Mannitol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Sorbitol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Xylitol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_ArtificialSweetenersTotal = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Aspartame = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Saccharin = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Alcohol = models.DecimalField(decimal_places=3, max_digits=20, default=0)
	week_Caffeine = models.DecimalField(decimal_places=3, max_digits=20, default=0)

	def __str__(self):
		return str(self.name)